### ISSUE TITLE
Translation mistakes

### ISSUE THREAD

**Issue by shemadolev** [HebrewBombManual/hebrewbombmanual.github.io#1]
Found some mistakes on translation. Some are minor, but some are very important.
For example: On page 7, the the translated text reads "Push buttons from **bottom to top**", while the original (and correct) instruction is to "Push **top to bottom**".
Do you have any editable version of the manual? Would like to help with correcting mistakes.

**Comment by erelado** [comment]
Hi @shemadolev and thanks for your report. I'm sorry for the late response but this mistake you've mentioned was something that got fixed a long time ago, basically after the first release.

This is a GitHub project just for this specific reason - anyone can contribute. You can download the files to your PC, make changes, and create a pull request to consolidate the changes.

Let me know if you need any help with that or if you found any more mistakes.
