### ISSUE TITLE
בנושא שעשעון המילים - טבלאות משוקפות

### ISSUE THREAD

**Issue by sgershon** [HebrewBombManual/hebrewbombmanual.github.io#2]
בPDF, הטבלאות מופיעות משוקפות שמאל\ימין - כך שלאורך כל העמוד ההוראות לא מדוייקות.

תודה!

**Comment by E-RELevant** [comment]
@sgershon Can you please specify in what pages it occurs? I couldn't find what you're talking about.

**Comment by erelado** [comment]
@sgershon Can you please specify in what version (regular/simplified) as well as pages it occurs? I couldn't find what you're talking about

**Comment by sgershon** [comment]
Page 9 of the regular manual, printing from PDF - thanks!

![image](https://user-images.githubusercontent.com/10831143/82838617-6a7cae00-9ed5-11ea-8859-52c6357ff942.png)

As you can see, the signs appear reverted left/right.

**Comment by erelado** [comment]
Are you using the version from https://hebrewbombmanual.github.io?

**Comment by sgershon** [comment]
You are right, the one in https://hebrewbombmanual.github.io/print/BombDefusalManual-v1-he-en.pdf seems to have the correct orientation. Thanks!

Was using: https://bombmanual.github.io/hebrew/print/BombDefusalManual-v1-he-en.pdf from https://bombmanual.github.io/hebrew/ . This one is reversed!

**Comment by erelado** [comment]
Yes, It seems like this version outdated. I'll try to ask for an update, as this is not my own project.
@brugnara would appreciate your help with that.

**Comment by brugnara** [comment]
I updated the "main" project. Let me know 👍
